# Configuration file. Made with ❤ by frafol.
# For support: discord.io/futuredevelopment

settings:

  update_check: true
  auto_update: true
  stats: true

  # You can choose to have your players' hide/show mode saved even after a restart.
  # This feature is disabled by default and requires a restart to be enabled.
  save_after_reboot: false

  # PlayerVisibility's usage permission.
  usage_permission: "playervisibility.usage"

  # PlayerVisibility's reload permission.
  reload_permission: "playervisibility.reload"

  # PlayerVisibility's bypass permission.
  # Players with this permission can see all players even if they are hidden.
  # When hiding/showing all players, players with this permission will be ignored, so they will be shown to all players.
  bypass_permission: "playervisibility.bypass"

messages:

  # General messages.
  usage: "&cUsage: &7/playervisibility <hide/show/reload>"
  no_permission: "&cYou don't have permission to use this command."
  reloaded: "&aConfiguration reloaded successfully."

  # Error messages.
  already_hidden: "&cAll players are already hidden."
  already_shown: "&cAll players are already shown."

  # Message sent to players when they hide/show all players.
  hidden: "&cAll players are now invisible."
  shown: "&aAll players are now visible."

  # Message sent to players when they join the server and player visibility is disabled.
  # Leave "none" to disable this feature.
  join_message: "&ePlayer visibility is currently disabled on this server."

worlds:

  # Toggle this feature.
  enabled: true

  # List of worlds where player visibility is ALWAYS enabled, even if disabled by an administrator.
  blacklisted_worlds:
    - "world_nether"
    - "world_the_end"

command:

  # PlayerVisibility's commands aliases.
  aliases:
    - "playervisibility"
    - "playerv"
    - "visibility"
    - "showplayers"
    - "show"
    - "sp"
    - "showp"
    - "hideplayers"
    - "hide"
    - "hp"
    - "hidep"